[target.x86_64-pc-windows-gnu]
# Use the cross-provided MingW image
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:latest"

[build]
# Specify podman as the container engine
container-engine = "podman"
